//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPlanning
    {
        public int idProject { get; set; }
        public int idSprint { get; set; }
        public int slot { get; set; }
        public Nullable<System.DateTime> planStart { get; set; }
        public Nullable<System.DateTime> planEnd { get; set; }
    
        public virtual tProject tProject { get; set; }
        public virtual tSprint tSprint { get; set; }
    }
}
