//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTrackRecord
    {
        public int idTrackRecord { get; set; }
        public int idTracker { get; set; }
        public Nullable<System.DateTime> activityStart { get; set; }
        public Nullable<System.DateTime> activityEnd { get; set; }
        public Nullable<int> activityTotal { get; set; }
    
        public virtual tTracker tTracker { get; set; }
    }
}
